from pathlib import Path


VIDEO_EXTENSIONS = {".mp4", ".mov", ".mkv", ".webm", ".avi", ".m4v"}
DEFAULT_OUTPUT_DIR = Path("output")
DEFAULT_LOG_DIR = Path("logs")

TASK_PENDING = "PENDING"
TASK_PROBING = "PROBING"
TASK_EXTRACTING_AUDIO = "EXTRACTING_AUDIO"
TASK_TRANSCRIBING = "TRANSCRIBING"
TASK_POST_PROCESSING = "POST_PROCESSING"
TASK_EXPORTING_SUBTITLE = "EXPORTING_SUBTITLE"
TASK_RENDERING = "RENDERING"
TASK_MUXING = "MUXING"
TASK_DONE = "DONE"
TASK_FAILED = "FAILED"
